name: 'checkout'
description: 'Delegate to actions/checkout'

inputs:
  ref:
    type: string
    required: false
    default: ''
  fetch-depth:
    type: number
    required: false
    default: 1

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: ${{ inputs.fetch-depth }}
